### ISSUE TITLE
Eclipse setup their gitlab. Why not us?

### ISSUE THREAD

**Issue by benoitc** [erlef/infra-wg#11]
Following their move in Europe, the Eclipse foundation have  also setup a Gitlab service to host all the repositories. It will comes in addition to their Github :

https://bugs.eclipse.org/bugs/show_bug.cgi?id=537913

They are mainly doing it to open the  Eclipse projects for more people and keep the control on the sources supported by the foundation. 

Coming with this idea of using the Foundation to host and maintain orphaned Erlang projects  I was thinking that Gitlab would perfectly fit. This could be done in addition to github and synchronize between the services if needed.

Also this is not the only foundation to have choosen that path. Kde, Gnome are also doing it.

## Pro:

* This solves our communications problems (issues can be private, good wiki support, discussions boards). 
* Match our values (especially about Opensource)
* The enterprise version is free for Opensource organizations :https://about.gitlab.com/solutions/open-source/ This will give good support of the sources  in the long term.
* We can host as many projects as we want, create subgroups (for example a group / WGs)
* We can host websites (Gitlab pages) with their own domains
* we can host our files for history
* We can set up rules
* Open for any one without US restrictions

## Cons:

* We have to maintain it, but can be mostly automated, this can be an issue still as we are not that many.

## Notes

Copying and mirroring our current Github to Gitlab is straight forward.
I propose the following agenda:

1. september setup setup test-gitlab.erlef.org, copy current github and invite WGs and community to place their projects. Only WGs will be able to create private projects. Other projects will be public.
2. january 2021: stable version 

Anyway  let's discuss and raise  the Pros/Cons about it in comments there.

**Comment by starbelly** [comment]
I have no issues going to gitlab what so ever. I generally prefer it. The only hitch is what you already stated, which is maintenance, and I would agree, it's generally automatic. We would have to back up to vultr object storage, in addition to image snapshots. 

There's only one thing I would not want us to maintain and that is a CI server. I don't think we really have a strong need for that, erlef website aside, but I do think we need a solid solution for that if we're on gitlab. This is an area I don't have any experience in, in that anytime I've run my own gitlab I've always run my own gitlab-ci server in conjunction with it, but that was part of my job 😁 

Do you have any thoughts on this?

**Comment by benoitc** [comment]
interresting to read : https://about.gitlab.com/blog/2020/09/08/gnome-follow-up/

**Comment by ahw59** [comment]
I should look out the IT budget numbers for Eclipse but I think they have more than a handful of full-time IT guys. I think we need to stay in SaaS land for the time being

**Comment by benoitc** [comment]
closing issue. no action since awhile.
