### ISSUE TITLE
why do some emails go in spam?

### ISSUE THREAD

**Issue by benoitc** [erlef/infra-wg#12]
Maybe worth to check if we miss some record in the DNS configuration?  This could explain why some mails may go in the spam folder.

**Comment by starbelly** [comment]
If this is Re: Daniel then it's not that his mails were going to spam, 
he wasn't getting emails on voting but it's because he's not a paying 
member.

**Comment by benoitc** [comment]
i think some other people had the mail arriving in the spam folder. check
is easy anyway will do over the weekend.

related to that specific point of membership i opened a ticket on the mkg
group

**Comment by benoitc** [comment]
i don't get enough mail these days coming from @erlef.org to see if they still going to spam. I assurme however dns is correctly setup, so let's close this ticket.
