### ISSUE TITLE
Offer alternative ways of logging into the site

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#20]
It has been suggested that we offer alternative ways of logging into the site and thus wild apricot. 

Currently suggestions : 

- Decentralized Identity integration / Oauth and ABTnode

**Comment by robroyhobbs** [comment]
Proposal to use ArcBlock DID:CONNECT Blocklet to run decentralized login/authentication service that can be integrated with OAuth, or just run as-is.

Note, does not require blockchain any required 3rd party dependencies are built into the software package. This is a simple authentication service and nothing more. 

1) Setup ABT Node on a free instance of t2.micro or equivalent.  When setting up the node, you will use decentralized identity to secure the node separate from the OS layer. 
2) Install and setup the Blocklet from the marketplace
3) Start the service and use the "Access URL" to login to the didconnect service.
4) Once there, you can enable any requirements - do we want name, email, etc. once saved then you can simply enable the service to make it work.  For some of the community services it is nice to have an email attached to an identity address so we can email, etc. 
5) There are various integration methods including simple react or oauth. 
6) Users will need to use the decentralized identity wallet.  The app for login/authenticate requires no PII, etc. 

for us, my preference is that the service remains under the control of eef versus just leveraging a hosted version to ensure any type of data generated remains under the control of eer. 

Blocklet: https://blocklet.arcblock.io/dapp/did-connect
Walkthrough: https://www.arcblock.io/en/decentralized-identity-developer-workshop/
Reference to the W3C identity method https://arcblock.github.io/abt-did-spec/

**Comment by starbelly** [comment]
This should be closed IMO. It's clear we don't have time or capacity to take this on at the moment. I don't think it should be altogether dismissed, but I'm not sure when we would be able to get to it and there's a lot to discuss in here.
