### ISSUE TITLE
Setup hootsuite for marketing group

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#27]
- includes setting up slack integrations, etc.

**Comment by starbelly** [comment]
Applied for non-profit discount with hootsuite. I expect this to take at least a few days. 

Edit: Correction, we got pre approved, waiting for Seb to create the account now.

**Comment by benoitc** [comment]
what are the requirements and who will use it? Do we have a list of the users? We need to keep a list of who will have access to it for privacy reasons. Also we probably need a privacy policy for that.

**Comment by starbelly** [comment]
@benoitc Primarily the marketing working group.

**Comment by starbelly** [comment]
Going to punt on setting up integrations, that should be its own ticket. Closing this as resolved.
