### ISSUE TITLE
Add generic server to poll wildapricot database ever N hours and sync.

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#44]
Because webhooks can fail, polling acts as a fail safe.

**Comment by benoitc** [comment]
how wil it be used? I sthis what will be availabel for others service s that want to access to wildapricot? Why not simply caching wildapricot results in a shared  memory database?

**Comment by benoitc** [comment]
move to website project?

**Comment by starbelly** [comment]
> how wil it be used? I sthis what will be availabel for others service s that want to access to wildapricot? Why not simply caching wildapricot results in a shared memory database?

This is simply to be used to make sure the cache in the website app and wildapricot are in sync in case of a webhook failure.  I'm not terribly sure how this would be useful outside of that context at the moment, but perhaps maybe could be in the future, and if so we could extract it. 

And yes, this should be moved to the website I believe. https://github.com/erlef/website/issues/285
