### ISSUE TITLE
nitpick: rename this repository to infra-wg

### ISSUE THREAD

**Issue by josevalim** [erlef/infra-wg#5]
To be consistent with all other wg. I also suggest adding a small README telling people to check the issues tracker. :) Example: https://github.com/erlef/documentation-wg Thanks!

**Comment by starbelly** [comment]
I don't disagree with this and we should do the same for marketing as well. Will wait for others to weigh in though. We can most certainly add a README now though.

**Comment by benoitc** [comment]
done
