### ISSUE TITLE
Consider switching from matomo to plausible

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#52]
Plausible offers pretty much a 1:1 solution for analytics (1:1 to matomo), the difference is plausible is part of our ecosystem. The app is open source, but I would not want to self-host. 

https://github.com/plausible/analytics

https://plausible.io/

Please add thoughts and/or concerns.

**Comment by starbelly** [comment]
https://plausible.io/vs-matomo#what-makes-plausible-a-great-matomo-alternative

**Comment by starbelly** [comment]
It's also hosted in the EU @benoitc 😁

**Comment by ahw59** [comment]
Sounds like a very good idea to me. Especially if it isn't too much work. We should certainly keep it in the family.

**Comment by starbelly** [comment]
It should be as simple as signing up, putting their simpler javascript snippet and such in place, create an account for marketing, and then call it a day :)

**Comment by benoitc** [comment]
@starbelly do we host the metrics ourself right now or do we use an external service?

**Comment by starbelly** [comment]
@benoitc we do not host ourselves

**Comment by benoitc** [comment]
@starbelly you closed the issue but what is the resolution?

**Comment by starbelly** [comment]
Sorry, I meant to close with comment. We have switched to plausible per executive decision.
