### ISSUE TITLE
Newsletter system split brain issue

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#55]
We kicked off with two newsletter systems (mailchimp and wildapricot) and we need  reduce to one in order to minimize the operative and administrative burdens that come with this, as well as confusion for members. 

 Mailchimp is nice, it's much nicer to work with IMO, but in order to really utilize it we would need to sync member email addresses to it and I'd prefer we not. 
 
Wildapricot is not as nice for creating newsletters, but it's there, it works, thus I'm in favor of just switching to it. I suggest changing the form to a link for joining us as well. The alternative is to add subscribes as contacts in wildapricot if we think a lot of people who wouldn't be members, subscribe to the news letter. But we also just post the newsletter on the site too, that's part of my rationale for wanting to it from subscribe form to a join us link.

**Comment by benoitc** [comment]
Is this enough tfor the marketing? What I find interesting in mailhchimp is the possibility to find that newsletter on the website after. Will it be possible with wild apricot? 

Also why exporting the member list? Isn't the newsletter independent from the mail to the members and then request an opt-in?

**Comment by starbelly** [comment]
Members can request to opt out of news letters via wildapricot, to be clear. I don't think the news letter should be seperate, we already have too many things in too many places IMO. Syncing members with mailchimp also is yet another thing to tick off in regards to a GDPR delete request. 

So, basically, I'm wanting to simplify and make things less confusing internally and externally. 

We can talk to the marcom team tomorrow about whether wildapricot is sufficient for their purposes, but I can not see why it would not be.

**Comment by starbelly** [comment]
Marketing team is good with wildapricot to note. We really don't need much since we're using a protocol suggested by @max-au. Specifically, tweets, emails (including news letters) generally shouldn't have much or any content to them, maybe a few brief words. Rather, they should link to something that can easily be changed, which emails, tweets, etc can not be.

Closing this as resolved.
