### ISSUE TITLE
Erlang/OTP release announcements in Slack

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/infra-wg#57]
As per a recent discussion in Slack, this Issue formalises the request to check if it's possible/desirable to have, in Erlang announcements, a message every time a new Erlang/OTP version is released. It would probably even be cooler if we could make this (e.g. an action) pluggable into other repo.s so that the maintainers don't have to keep doing the posts manually.

**Comment by eproxus** [comment]
Hi! I’m the one who set up the messages for Erlang itself. It’s currently being done via Zapier, sponsored by Peer Stritzinger GmbH. It’s a simple Zapier task that checks for new GitHub releases and posts a message in Slack.

(If someone who is admin in the Elixir slack wants the same for Erlang and even Elixir there, let me know. I’d be happy to set it up. I’ve asked in the admin channel there before but didn’t receive any response).

This mechanism could be extended to other repos, but I’m not sure Zapier can be automated that way. This would mean that someone would have to enable new tasks for each repo that should be announced.

A user could of course enable their own Zapier task to post as themselves if they want.

My gut feeling says that if anyone could subscribe any repo for notifications in the announcements channel it would quickly become too noisy. Would appreciate a discussion around this though. Perhaps there could be more notification channels for libraries etc.

**Comment by eproxus** [comment]
Perhaps a more generic system could be built with GitHub Actions. We could even have a repo with a list of other repos that should be monitored for notifications.

**Comment by paulo-ferraz-oliveira** [comment]
cc: @starbelly

**Comment by eproxus** [comment]
Btw, if anyone wants to copy the Zap it's here https://zapier.com/shared/7d8da6025b74898b687299eb4750e50ee82e9e16

**Comment by starbelly** [comment]
Let's wait until this breaks again and perhaps require more user input as to whether this of value to the community for this group to take on this burden.
