### ISSUE TITLE
Logging service

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#58]
We make use of journalctl for viewing logs, but in general, and especially in regards to long history this is sub-optimal. We need a simple logging service (i.e., that's all it does). https://logflare.app/ comes to mind first.

**Comment by ahw59** [comment]
Bryan, please go ahead and set this up ASAP. we need a transaction record. It was quite embarrassing today to appligoze to the ElixirAfrica folks. I had insisted they sign their event up, and then they told me they had 3 weeks ago to no avail... (shot myself in the foot with that one)

**Comment by starbelly** [comment]
Will do. On the incident, I'm not convinced there's anything wrong. I mean, something went wrong, but as to what is an unknown. I just did a test submission, no problems. 

But also, I'm wondering why they didn't reach out 🤔

**Comment by starbelly** [comment]
This was resolved via https://github.com/erlef/website/pull/316
