### ISSUE TITLE
Academic projects EEF mailing list

### ISSUE THREAD

**Issue by natalia-chechina** [erlef/infra-wg#62]
Hello,

Could you, please, create a mailing list for sending updates and news to academics related to EEF projects? e.g. academia@... Initially, we'd like to use this mailing list to send project ideas suggested by the EEF community that can be done as part of the final year and MSc projects.
* The projects can be seen by the wider community (in case there will be a wider interest in the projects).
* However, when universities reply we need to have "private" communication with individual people -- can we also have an email address to which 2-3 eef members have access?
* I was also wondering if we can include some emails in the mailing list from the beginning (allowing people to unsubscribe if they want to)?

**Comment by max-au** [comment]
This has been done, and @natalia-chechina  assigned as mailing list owner.

**Comment by starbelly** [comment]
Closing this as resolved.
