### ISSUE TITLE
Help with hosting new erlang.org site

### ISSUE THREAD

**Issue by KennethL** [erlef/infra-wg#63]
This is a request or rather question at this point from the OTP team regarding if the EEF infra structure WG can assist in hosting a redirect service for the `erlang.org`website.

What we need help to host is: https://github.com/erlang/erlang-org/tree/beta

It is a static website generated using jekyll and a couple of escripts. It can be delivered completely as static assets, no need for a statefull server.

During the beta we hosted the entire site on github pages and the plan was that we were going to continue to do so for the main site. However, in order for external tools to work correctly we need to have some http level redirects from www.erlang.org to erlang.org. To understand why this is needed you need to understand a bit about how the current www.erlang.org is hosted.

At the moment we have:
- the dns of www.erlang.org to point to a server hosted by Erlang Solutions. This is what runs a cowboy server, a psql database and all the code here: https://github.com/erlang/erlang-org/.
- the dns of erlang.org to point to an Ericsson server. Here we host the contents of the /downloads folder and some other things.

We have then setup http redirects using nginx so that if you access https://www.erlang.org/downloads you will be redirected to https://erlang.org/downloads. If you access https://erlang.org you will be redirected to https://www.erlang.org. i.e. depending on where the actual content is, the servers will redirect you to the correct place.

The problem that we now are facing is that because we have always redirected some URLs from www.erlang.org to erlang.org tools rely on it. I've sent a PR to kerl (https://github.com/kerl/kerl/pull/383) to fix it there, but if there is one tool that relies on that redirect, there is bound to be more.

So what we need is to have something that can host our static content over https and issue redirects to erlang.org for some URLs.

Lukas

**Comment by starbelly** [comment]
I'm 💯 all for this. We can easily spin up a simple web server for this to at least handle the redirects. It may be advantageous to keep the hosting of the site on github to simplify your automated deployment, but we will have to experiment a bit with that. That said, most complicated setup would be a ci/cd pipeline that uploads assets to the web server.

**Comment by peerst** [comment]
I'm for going forward with netlify

**Comment by benoitc** [comment]
+1  for me as well, let's figure the details during our next meeting .

**Comment by starbelly** [comment]
> I'm for going forward with netlify

Agreed. Best solution for all is netlify which the EEF via infrastructure working group will gladly sponsor.

**Comment by max-au** [comment]
Agree with this.

**Comment by starbelly** [comment]
This has been launched. Won't close the ticket yet as we need to get netlify in our wiki first.

**Comment by starbelly** [comment]
Added  a brief description here for tracking purposes : https://github.com/erlef/infra-wg/wiki/Netlify

There isn't much else to say. Closing this as resolved.
