### ISSUE TITLE
Setup SPF erlef.org  

### ISSUE THREAD

**Issue by starbelly** [erlef/infra-wg#66]
There currently is no spf record set for erlef.org or any of it's sub-domains. This can result in messages getting flagged as spam by other providers. 

spf record setup referenced here : https://www.fastmail.help/hc/en-us/articles/360060591153-Domains-Advanced-configuration

**Comment by benoitc** [comment]
We didn't assign the DNS to fast mail right?

**Comment by max-au** [comment]
We host DNS with Namecheap.

I clearly recall setting up SPF (but not DKIM/DMARC) for WildApricot, but I guess I did not document the setup so it is likely to be incomplete or even wrong.

**Comment by starbelly** [comment]
I'll take a look shortly.

**Comment by starbelly** [comment]
@max-au It looked fine to me. I need to get with you on further on how ci.erlef.org is configured. I did modify to a softfail `~all` as was worried about rejections. 

Fastmail seems to recommend a neutral all `?all`, but a softfail I think makes more sense. Will revisit further tomorrow. 

Edit:

Note: I also configured dkim.

**Comment by starbelly** [comment]
I went ahead and looked at this further. The only thing open left to discuss is whether to use hard fail, soft fail, or even neutral. 

The happy medium of `~all` once again makes sense to me in general, but it's possible the safest choice is neutral.  

This fastmail write up about the problems with SPF I believe highlights why they went with `?all` (neutral) : https://fastmail.blog/advanced/spf-dkim-dmarc/

**Comment by max-au** [comment]
It appears working for me, should we close it now?
