### ISSUE TITLE
Weed Maps Logo

### ISSUE THREAD

**Issue by francescoc** [erlef/infra-wg#68]
Can we please add Weedmaps 
https://v.fastcdn.co/u/de6a250c/51852861-0-WM-2020.png

to the sponsor page?

**Comment by francescoc** [comment]
@benoitc

**Comment by starbelly** [comment]
@francescoc This is done. Check it out before we close out the issue.

**Comment by benoitc** [comment]
@francescoc ?

**Comment by starbelly** [comment]
Closing as resolved
