### ISSUE TITLE
New Sponsor

### ISSUE THREAD

**Issue by francescoc** [erlef/infra-wg#72]
Hi,
Can you please add HCA healthcare logo to the sponsors page: https://media-exp2.licdn.com/dms/image/C4E0BAQGN32sqDLxzNg/company-logo_200_200/0/1609865012021?e=1664409600&v=beta&t=NNNVF9va_pi9VG8o930nIPwATPmyr5RqUsu5THaPjzo

**Comment by starbelly** [comment]
Resolved.
