### ISSUE TITLE
Sponsorship Logo Change

### ISSUE THREAD

**Issue by francescoc** [erlef/infra-wg#74]
Simpli.fi has rebranded to Mainmatter: https://mainmatter.com/blog/2022/09/18/simplabs-becomes-mainmatter/

Can you please update the logo and any links on the sponsorship page? New Logo attached. 
<img width="415" alt="mainmatter" src="https://user-images.githubusercontent.com/979065/191007641-4cc4daa6-653a-4a75-bba6-443b60b24cd9.png">

**Comment by francescoc** [comment]
Apparently, they sent a pull request for the website. If ok, please merge it.

**Comment by starbelly** [comment]
Done 😄
