### ISSUE TITLE
Add our AGM reports to public records page

### ISSUE THREAD

**Issue by sstrollo** [erlef/infra-wg#77]
We should have 2020 - 2022 AGM reports available on our public records page: https://erlef.org/public_records/

2022
Chairs Report: https://drive.google.com/file/d/1PsfBFJrWEeVoR8ZIMP8u05-kemmk9QEV/
Financial Report: https://drive.google.com/file/d/1X1sOCcvX_jODzEdhPNCAd2qFsC2VVosr/

2021
Chairs Report https://drive.google.com/file/d/1TA-7aMMJpHcot9Syo-XSP3RSfXjP6ipa/
Financial Report https://drive.google.com/file/d/1yUs4TslvGM_RPA9RkfUHfWAVu2m8qduC/

2020
Chairs Report https://drive.google.com/file/d/1D2iGQPtZ9RpxFi7c246wik2TGhyt4rvh/
Financial Report https://drive.google.com/file/d/1EOhWz8d0z-QWsPFd4QuZeX3XJB95Ujbe/

**Comment by starbelly** [comment]
Will get this done by EOD tomorrow. Thanks @sstrollo !

**Comment by starbelly** [comment]
This has been done. Thanks again @sstrollo
