### ISSUE TITLE
new sponsor logo, smartrent

### ISSUE THREAD

**Issue by sstrollo** [erlef/infra-wg#78]
Please add logo with link to https://smartrent.com/ for our new sponsor - thanks!! (Attached both as png and svg)

/Sebastian

![20220630-SR-primary-color](https://github.com/erlef/infra-wg/assets/2486859/fc5f13b6-1e4e-49ec-bc7f-0911f8173970)
![20220630-SR-primary-color](https://github.com/erlef/infra-wg/assets/2486859/50148a8c-c24f-4aca-a455-879d7797e16b)

**Comment by starbelly** [comment]
@sstrollo  Done! :)
